apiVersion: v1
kind: ConfigMap
metadata:
  name: {{PID-APP}}-cmaps
data:
  # property-like keys; each key maps to a simple value
  # GS_PROJECT_ID: 'devops-penal'
  # GS_MEDIA_BUCKET_NAME: 'ledc-media-prod'
  # DEBUG: 'False'
  # ALLOWED_HOSTS: 'led.pjm.gob.ar'
  