apiVersion: apps/v1 
kind: Deployment
metadata:
  name: {{PID-APP}}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    spec:
      containers:
      - name: {{PID-APP}}
        image: {{IMAGE-NAME}}
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{PID-APP}}-sensible-settings-{{ENV}}
        - configMapRef:
            name: {{PID-APP}}-cmaps-{{ENV}}
        volumeMounts:
          - name: uwsgi-config
            mountPath: /app/uwsgi.ini
            subPath: uwsgi.ini
            readOnly: true
      volumes:
        - name: uwsgi-config
          configMap:
            name: {{PID-APP}}-cm-uwsgi-{{ENV}}


      imagePullSecrets:
      - name: {{PULL-REGISTRY-NAME}}