---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{PID-APP}}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{BASE-URL}}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{APP-ID}}  
      port: 80
    middlewares:
    - name: strippath-{{APP-ID}}
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{PID-APP}}-http
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{BASE-URL}}`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: {{APP-ID}}  
      port: 80