generatorOptions:
  disableNameSuffixHash: true
  
bases:
  - ../../base
  
namespace: {{NAMESPACE}}

nameSuffix: -{{ENV}}
commonLabels:
    app: {{NAME-PROJECT}}
    env: {{ENV}}

patchesStrategicMerge:
  - ingress-route.yaml
  - deployment.yaml
  - middleware.yaml


